[[sources]]
type = "github"
owner = "mgit-at"
repo = "nixos-common"

[[sources]]
type = "github"
owner = "mgit-at"
repo = "nix-unify"

[[sources]]
type = "github"
owner = "mgit-at"
repo = "cert-viewer"

[[sources]]
type = "github"
owner = "mgit-at"
repo = "hetzner-robot-failover-keepalived"
