name: "Frontend: Build & Deploy to Netlify"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "frontend/**"
      - "VERSION"

  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}



    - name: Building search.nixos.org
      run: |
        nix -vL build .#frontend
        mkdir ./dist
        cp -RL ./result/* ./dist/

    - name: Deploy to nixos-search.mgit.at
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" > deploy
        chmod 700 deploy
        rsync -ravpd -e"ssh -o StrictHostKeyChecking=no -i deploy" dist/ deploy@misc-public.mgit.at:
      if: github.repository_owner == 'mgit-at'
